### ISSUE TITLE
Some state codes do not match ISO 3166-2 standard

### ISSUE THREAD

**Issue by lucasrodes** [india-covid19vaccine/india-covid19vaccine.github.io#2] opened 2021-02-09 21:58 UTC
Hi,
I have noticed that some of the codes used in your data do not follow the [ISO 3166-2 codes](https://en.wikipedia.org/wiki/ISO_3166-2:IN). In particular, these are:

| State | Code currently used | ISO 3166-2 code |
|-------|---------------------|-----------------|
|   Chhattisgarh    |       CG              |        CT         |
|    Odisha   |         OD            |        OR         |
|   Tripura    |          TS           |          TR       |
|   Telangana    |        TR             |        TG         |
|   Uttarakhand    |        UK             |        UT         |

I think that using standardized 3166-2 for all states would be great. Would you consider changing these?

Thanks!

**Comment by sanyam-git** [comment] 2021-02-10 10:35
Thanks for notifying about it. Earlier I was thinking of going with the ISO codes too but later went with the vehicle registration code of the states. (some of the vehicle codes are different then the ISO codes as you can in the notes section [here](https://en.wikipedia.org/wiki/ISO_3166-2:IN#Current_codes)).
Currently I am not sure what's best for use here. I will decide and fix it if needed.
Thanks for you contribution  :)

**Comment by lucasrodes** [comment] 2021-02-10 15:11
Thanks for your response @sanyam-git. and your work. Also for the reference, interesting to discover this other standard :)

I will be using a small dictionary to map from vehicle to ISO codes, so not a big problem.

Cheers!

**Comment by sanyam-git** [comment] 2021-02-11 07:35
@lucasrodes , thanks for being considerate. A dictionary map will be good. (the reason I am keeping these codes instead of the ISO ones because these are in more popular in local use)
Although I found out about that I exchanged the code for Tripura and Telangana. So I have fixed them both as following:
- Telangana -> TS
- Tripura -> TR

I browsed a bit through your project, great work !

P.S. - if you feel that the issue is resolved you can close the issue.

**Closed as completed** 2021-02-13 14:48 UTC
